# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: en-US

# Site title
title: "Harith Arsyad"

# A description of your site for meta tag, search engine results.
description_header: "Hello! &#128075"
description: "I am an Electrical Engineering student at Iowa State
University, with a particular interest in power systems and VLSI design.
After completing my undergraduate degree, I plan on working in the industry
and applying everything I've learned in these past few years. I'm looking
forward to learning more from people who have been in this field for a long
time and seeing how this industry evolves over the years."

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: ""

# The base hostname & protocol of your site for where absolute urls are needed.
url: "https://haritharsyad.github.io/"

# Favicon
favicon: images/favicon.png

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: ""

# Site navigation - each item must have a title and a url.
navigation:
  - text: Home
    url: /
  - text: Resume
    url: files/Resume.pdf

# The shortname for your Disqus site to enable comments.
disqus: haritharsyad

# Colors
accent_color: '#ffffff'

# Site footer
footer:
  content: ""
  has_social: true

# Plugins
plugins:
  - jekyll-paginate

# http://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: '/page:num/'


# Permalinks
permalink: /:title

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
